<?php

declare(strict_types=1);

namespace SimpleKuma\TrafficSource;

/**
 * Traffic source templates for "Create from Template" (not auto-seeded on fresh install).
 */
class TrafficSourceTemplates
{
    private static function tok(string $name, string $parameter, string $placeholder): array
    {
        return [
            'name' => $name,
            'parameter' => $parameter,
            'placeholder' => $placeholder,
            'pass_to_lp' => false,
            'pass_to_offer' => false,
        ];
    }

    /** @return array<string, array<string, mixed>> */
    public static function all(): array
    {
        return [
            'facebook' => [
                'name' => 'Facebook',
                'cost_tracking_method' => 'integrated_api',
                'cost_param_key' => '',
                'cost_currency' => 'USD',
                'cost_tier' => TrafficSourceCostStatus::TIER_LIVE_API,
                'blurb' => 'Ad ID, ad set, campaign tracking',
                'tokens' => [
                    self::tok('Target/Keyword', 'source', '{{site_source_name}}'),
                    self::tok('Cost', 'cost', ''),
                    self::tok('External ID', 'fbclid', ''),
                    self::tok('Ad ID', 'ad_id', '{{ad.id}}'),
                    self::tok('Ad Set ID', 'adset_id', '{{adset.id}}'),
                    self::tok('Campaign ID', 'campaign_id', '{{campaign.id}}'),
                    self::tok('Ad Name', 'ad_name', '{{ad.name}}'),
                    self::tok('Ad Set Name', 'adset_name', '{{adset.name}}'),
                    self::tok('Campaign Name', 'campaign_name', '{{campaign.name}}'),
                    self::tok('Placement', 'placement', '{{placement}}'),
                ],
            ],
            'google' => [
                'name' => 'Google Ads',
                'cost_tracking_method' => 'integrated_api',
                'cost_param_key' => '',
                'cost_currency' => 'USD',
                'cost_tier' => TrafficSourceCostStatus::TIER_LIVE_API,
                'blurb' => 'GCLID / WBRAID / GBRAID, keyword, device tracking',
                'tokens' => [
                    self::tok('Target/Keyword', 'keyword', '{keyword}'),
                    self::tok('Cost', 'cost', ''),
                    self::tok('External ID', 'gclid', ''),
                    self::tok('WBRAID', 'wbraid', ''),
                    self::tok('GBRAID', 'gbraid', ''),
                    self::tok('Ad / Creative', 'ad', '{creative}'),
                    self::tok('Ad Group ID', 'adgroup', '{AdGroupId}'),
                    self::tok('Campaign ID', 'campid', '{CampaignId}'),
                    self::tok('Network', 'network', '{network}'),
                    self::tok('Device', 'device', '{Device}'),
                    self::tok('Interest Location', 'locinter', '{loc_interest_ms}'),
                    self::tok('Physical Location', 'locphys', '{loc_physical_ms}'),
                ],
            ],
            'youtube' => [
                'name' => 'YouTube',
                'cost_tracking_method' => 'integrated_api',
                'cost_param_key' => '',
                'cost_currency' => 'USD',
                'cost_tier' => TrafficSourceCostStatus::TIER_LIVE_API,
                'blurb' => 'Video placement + GCLID / WBRAID / GBRAID',
                'tokens' => [
                    self::tok('Target/Keyword', 'placement', '{placement}'),
                    self::tok('Cost', 'cost', ''),
                    self::tok('External ID', 'gclid', ''),
                    self::tok('WBRAID', 'wbraid', ''),
                    self::tok('GBRAID', 'gbraid', ''),
                    self::tok('Ad / Creative', 'ad', '{creative}'),
                    self::tok('Ad Group ID', 'adgroup', '{AdGroupId}'),
                    self::tok('Campaign ID', 'campid', '{CampaignId}'),
                    self::tok('Network', 'network', '{network}'),
                    self::tok('Device', 'device', '{Device}'),
                    self::tok('Interest Location', 'locinter', '{loc_interest_ms}'),
                    self::tok('Physical Location', 'locphys', '{loc_physical_ms}'),
                ],
            ],
            'tiktok' => [
                'name' => 'TikTok',
                'cost_tracking_method' => 'manual_token',
                'cost_param_key' => 'cost',
                'cost_currency' => 'USD',
                'cost_tier' => TrafficSourceCostStatus::TIER_MANUAL_URL,
                'blurb' => 'TikTok Ads click and campaign tokens',
                'tokens' => [
                    self::tok('Target/Keyword', 'placement', '__PLACEMENT__'),
                    self::tok('Cost', 'cost', ''),
                    self::tok('External ID', 'ttclid', '__CLICKID__'),
                    self::tok('TS Campaign ID', 'campaign_id', '__CAMPAIGN_ID__'),
                    self::tok('TS Campaign Name', 'campaign_name', '__CAMPAIGN_NAME__'),
                    self::tok('Ad Group', 'adset', '__AID__'),
                    self::tok('Ad Group Name', 'adset_name', '__AID_NAME__'),
                    self::tok('Ad Creative ID', 'creative', '__CID__'),
                    self::tok('Ad Name', 'creative_name', '__CID_NAME__'),
                ],
            ],
            'zeropark' => [
                'name' => 'Zeropark',
                'cost_tracking_method' => 'manual_token',
                'cost_param_key' => 'cost',
                'cost_currency' => 'USD',
                'cost_tier' => TrafficSourceCostStatus::TIER_MANUAL_URL,
                'blurb' => 'Pop and domain traffic tokens',
                'tokens' => [
                    self::tok('Target/Keyword', 'keyword', '{keyword}'),
                    self::tok('Cost', 'cost', '{visit_cost}'),
                    self::tok('External ID', 'click_id', '{cid}'),
                    self::tok('TS Campaign ID', 'campaign_id', '{campaign_id}'),
                    self::tok('TS Campaign Name', 'campaign_name', '{campaign_name}'),
                    self::tok('Source', 'source', '{source}'),
                    self::tok('Target', 'target', '{target}'),
                    self::tok('Match Type', 'match_type', '{match}'),
                    self::tok('Traffic Type', 'traffic_type', '{traffic_type}'),
                    self::tok('Country', 'country', '{geo}'),
                    self::tok('Visitor Type', 'visitor_type', '{visitor_type}'),
                    self::tok('OS', 'os', '{os}'),
                    self::tok('Device ID', 'device_id', '{device_id}'),
                    self::tok('Browser', 'browser', '{browser}'),
                    self::tok('Carrier', 'carrier', '{carrier}'),
                    self::tok('Target URL', 'landing_url', '{target_url}'),
                ],
            ],
            'taboola' => [
                'name' => 'Taboola',
                'cost_tracking_method' => 'manual_token',
                'cost_param_key' => 'cost',
                'cost_currency' => 'USD',
                'cost_tier' => TrafficSourceCostStatus::TIER_MANUAL_URL,
                'blurb' => 'Native ads publisher tokens',
                'tokens' => [
                    self::tok('Target/Keyword', 'publisher_site', '{site}'),
                    self::tok('Cost', 'cost', '{cpc}'),
                    self::tok('External ID', 'click_id', '{click_id}'),
                    self::tok('Creative', 'creative_name', '{creative_name}'),
                    self::tok('Creative ID', 'custom_id', '{custom_id}'),
                    self::tok('Title', 'title', '{title}'),
                    self::tok('Thumbnail', 'thumbnail', '{thumbnail}'),
                    self::tok('Platform', 'platform', '{platform}'),
                    self::tok('TS Campaign ID', 'campaign_id', '{campaign_id}'),
                    self::tok('Campaign Item', 'campaign_item', '{campaign_item_id}'),
                    self::tok('Publisher ID', 'site_id', '{site_id}'),
                    self::tok('Site Domain', 'site_domain', '{site_domain}'),
                    self::tok('TS Campaign Name', 'campaign_name', '{campaign_name}'),
                ],
            ],
            'mgid' => [
                'name' => 'MGID',
                'cost_tracking_method' => 'manual_token',
                'cost_param_key' => 'cost',
                'cost_currency' => 'USD',
                'cost_tier' => TrafficSourceCostStatus::TIER_MANUAL_URL,
                'blurb' => 'Widget, teaser, and geo tokens',
                'tokens' => [
                    self::tok('Target/Keyword', 'widget', '{widget_id}'),
                    self::tok('Cost', 'cost', '{click_price}'),
                    self::tok('External ID', 'clkid', '{click_id}'),
                    self::tok('Ad ID', 'adid', '{teaser_id}'),
                    self::tok('TS Campaign ID', 'campid', '{campaign_id}'),
                    self::tok('Category', 'catid', '{category_id}'),
                    self::tok('Country', 'geo', '{geo}'),
                    self::tok('City/Region', 'geor', '{geo_region}'),
                    self::tok('UserID', 'uis', '{user_id}'),
                    self::tok('IFA', 'ifa', '{ifa}'),
                    self::tok('PhonePrice', 'ppr', '{price_range}'),
                    self::tok('TeaserTitle', 'title', '{title}'),
                ],
            ],
            'rollerads' => [
                'name' => 'RollerAds',
                'cost_tracking_method' => 'manual_token',
                'cost_param_key' => 'cost',
                'cost_currency' => 'USD',
                'cost_tier' => TrafficSourceCostStatus::TIER_MANUAL_URL,
                'blurb' => 'Push and pop traffic tokens',
                'tokens' => [
                    self::tok('Target/Keyword', 'zone_id', '{zoneId}'),
                    self::tok('Cost', 'cost', '{cost}'),
                    self::tok('External ID', 'click_id', '{clickId}'),
                    self::tok('Creative ID', 'creative_id', '{creativeId}'),
                    self::tok('Feed ID', 'feed_id', '{feedId}'),
                    self::tok('TS Campaign ID', 'campaign_id', '{campaignId}'),
                    self::tok('TS Device', 'device', '{device}'),
                    self::tok('TS Browser', 'browser', '{browser}'),
                    self::tok('TS OS', 'os', '{os}'),
                    self::tok('TS Country Code', 'country_code', '{country}'),
                    self::tok('TS ISP', 'isp', '{isp}'),
                    self::tok('TS Carrier', 'carrier', '{carrier}'),
                    self::tok('TS Browser Version', 'browser_version', '{browserVersion}'),
                    self::tok('TS OS Version', 'os_version', '{osVersion}'),
                    self::tok('TS Country Name', 'country_name', '{countryName}'),
                    self::tok('TS Connection Type', 'connection_type', '{connectionType}'),
                    self::tok('TS User Agent', 'user_agent', '{UserAgent}'),
                    self::tok('TS Age Group', 'age_group', '{ageGroup}'),
                    self::tok('TS Format', 'format', '{format}'),
                ],
            ],
            'richads' => [
                'name' => 'RichAds',
                'cost_tracking_method' => 'manual_token',
                'cost_param_key' => 'cost',
                'cost_currency' => 'USD',
                'cost_tier' => TrafficSourceCostStatus::TIER_MANUAL_URL,
                'blurb' => 'Push notification tokens',
                'tokens' => [
                    self::tok('Target/Keyword', 'site_id', '[SITE_ID]'),
                    self::tok('Cost', 'cost', '[BID_PRICE]'),
                    self::tok('External ID', 'click_id', '[CLICK_ID]'),
                    self::tok('Creative ID', 'creative_id', '[CREATIVE_ID]'),
                    self::tok('Subscriber List ID', 'sublist_id', '[SUB_LIST_ID]'),
                    self::tok('Publisher ID', 'publisher_id', '[PUBLISHER_ID]'),
                    self::tok('TS Campaign ID', 'campaign_id', '[CAMPAIGN_ID]'),
                    self::tok('TS Campaign Name', 'campaign_name', '[CAMPAIGN_NAME]'),
                    self::tok('OS', 'os', '[OS]'),
                    self::tok('Country', 'country', '[COUNTRY]'),
                    self::tok('Region', 'region', '[REGION]'),
                    self::tok('City', 'city', '[CITY]'),
                    self::tok('IP', 'ip', '[IP]'),
                ],
            ],
            'rumble' => [
                'name' => 'Rumble',
                'cost_tracking_method' => 'integrated_api',
                'cost_param_key' => '',
                'cost_currency' => 'USD',
                'cost_tier' => TrafficSourceCostStatus::TIER_VARIABLES_ONLY,
                'blurb' => 'Native video — tokens only until API cost ships',
                'tokens' => [
                    self::tok('Target/Keyword', 'site_domain', '{site.domain}'),
                    self::tok('External ID', 'click_id', '{click}'),
                    self::tok('Creative', 'creative', '{creative}'),
                    self::tok('Site ID', 'site_id', '{site}'),
                    self::tok('Ad Zone', 'ad_zone', '{adzone}'),
                    self::tok('TS Campaign ID', 'campaign_id', '{campaign}'),
                    self::tok('Lander ID', 'lander_id', '{lander}'),
                    self::tok('TS Country ID', 'country_id', '{country.id}'),
                    self::tok('TS Country Name', 'country_name', '{country}'),
                    self::tok('TS Region ID', 'region_id', '{region}'),
                    self::tok('TS City ID', 'city_id', '{city}'),
                    self::tok('TS City Name', 'city_name', '{city.name}'),
                    self::tok('TS Carrier ID', 'carrier_id', '{carrier}'),
                    self::tok('TS Device ID', 'device_id', '{device}'),
                    self::tok('TS Device Type', 'device_type', '{device.type}'),
                    self::tok('TS OS ID', 'os_id', '{os}'),
                    self::tok('TS OS Name', 'os_name', '{os.name}'),
                    self::tok('TS OS Version', 'os_version', '{os.version}'),
                    self::tok('TS Language ID', 'language_id', '{language}'),
                    self::tok('Keywords', 'keywords', '{keywords}'),
                ],
            ],
            'outbrain' => [
                'name' => 'Outbrain',
                'cost_tracking_method' => 'integrated_api',
                'cost_param_key' => '',
                'cost_currency' => 'USD',
                'cost_tier' => TrafficSourceCostStatus::TIER_VARIABLES_ONLY,
                'blurb' => 'Native ads — tokens only until API cost ships',
                'tokens' => [
                    self::tok('Target/Keyword', 'publisher_name', '{{publisher_name}}'),
                    self::tok('External ID', 'click_id', '{{ob_click_id}}'),
                    self::tok('Ad ID', 'ad_id', '{{ad_id}}'),
                    self::tok('Document Title', 'doc_title', '{{doc_title}}'),
                    self::tok('Document Author', 'doc_author', '{{doc_author}}'),
                    self::tok('Ad Title', 'ad_title', '{{ad_title}}'),
                    self::tok('Source ID', 'source_id', '{{source_id}}'),
                    self::tok('Promoted Link ID', 'promoted_link_id', '{{promoted_link_id}}'),
                    self::tok('TS Campaign ID', 'campaign_id', '{{campaign_id}}'),
                    self::tok('Section Name', 'section_name', '{{section_name}}'),
                    self::tok('Publisher ID', 'publisher_id', '{{publisher_id}}'),
                ],
            ],
            'bing' => [
                'name' => 'Bing Ads',
                'cost_tracking_method' => 'integrated_api',
                'cost_param_key' => '',
                'cost_currency' => 'USD',
                'cost_tier' => TrafficSourceCostStatus::TIER_VARIABLES_ONLY,
                'blurb' => 'Microsoft Ads — API cost sync coming soon',
                'tokens' => [
                    self::tok('Target/Keyword', 'keyword', '{keyword}'),
                    self::tok('External ID', 'msclkid', ''),
                    self::tok('Ad ID', 'ad', '{AdId}'),
                    self::tok('Ad Group ID', 'adgroup', '{AdGroupId}'),
                    self::tok('TS Campaign ID', 'campid', '{CampaignId}'),
                    self::tok('Match Type', 'match', '{MatchType}'),
                    self::tok('Order Item ID', 'itemid', '{OrderItemId}'),
                    self::tok('Product ID', 'prodid', '{ProductId}'),
                    self::tok('Target ID', 'targetid', '{TargetId}'),
                ],
            ],
            'newsbreak' => [
                'name' => 'NewsBreak',
                'cost_tracking_method' => 'integrated_api',
                'cost_param_key' => '',
                'cost_currency' => 'USD',
                'cost_tier' => TrafficSourceCostStatus::TIER_VARIABLES_ONLY,
                'blurb' => 'NewsBreak Ads — API cost sync coming soon',
                'tokens' => [
                    self::tok('Target/Keyword', 'creative_name', '__CREATIVE_NAME__'),
                    self::tok('External ID', 'click_id', '__CALLBACK_PARAM__'),
                    self::tok('Ad ID', 'ad_id', '__CREATIVE_ID__'),
                    self::tok('OS', 'os', '__OS__'),
                    self::tok('TS Campaign ID', 'campaign_id', '__CAMPAIGN_ID__'),
                    self::tok('TS Campaign Name', 'campaign_name', '__CAMPAIGN_NAME__'),
                    self::tok('Ad Set Name', 'adset_name', '__FLIGHT_NAME__'),
                    self::tok('Ad Set ID', 'adset_id', '__FLIGHT_ID__'),
                ],
            ],
        ];
    }

    /** @return list<array<string, mixed>> */
    public static function getSections(): array
    {
        return [
            [
                'title' => 'Live API cost (built-in)',
                'description' => 'Facebook and Google/YouTube cost sync is built into Kuma (Settings → Integrations).',
                'template_keys' => ['facebook', 'google', 'youtube'],
            ],
            [
                'title' => 'Manual cost (URL parameter)',
                'description' => 'Tracking tokens plus cost via URL when the network sends it (e.g. ?cost=…).',
                'template_keys' => ['tiktok', 'zeropark', 'taboola', 'mgid', 'rollerads', 'richads'],
            ],
            [
                'title' => 'API integrations — cost sync coming soon',
                'description' => 'Token maps for API-based networks. Clicks and breakdowns work; automatic cost pull is not built in yet (report cost may stay at zero).',
                'template_keys' => ['bing', 'rumble', 'outbrain', 'newsbreak'],
                'warning' => true,
            ],
        ];
    }

    public static function forJavaScript(): string
    {
        return json_encode(self::all(), JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP);
    }
}
