<?php
// Short Links (Masked Redirects) Page
require_once __DIR__ . '/../config/config.php';

// Handle file generation and download
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action']) && $_POST['action'] === 'generate') {
    $urlToMask = trim($_POST['url_to_mask'] ?? '');
    $passParameters = isset($_POST['pass_parameters']) && $_POST['pass_parameters'] === '1';
    
    // Validate URL
    if (empty($urlToMask) || !filter_var($urlToMask, FILTER_VALIDATE_URL)) {
        $error = 'Please enter a valid URL to mask.';
    } else {
        // Generate PHP redirect file
        $fileName = 'redirect.php';
        
        if ($passParameters) {
            $fileContent = '<?php
/**
 * Kuma Short Link - Generated by Simple KUMA
 * Use on landing page CTA buttons to mask your tracking URL.
 */

$targetUrl = "' . addslashes($urlToMask) . '";

// Append all query parameters from the current request
$queryString = $_SERVER[\'QUERY_STRING\'] ?? \'\';
if (!empty($queryString)) {
    $targetUrl .= (strpos($targetUrl, \'?\') === false ? \'?\' : \'&\') . $queryString;
}

header("Location: " . $targetUrl, true, 302);
exit;
?>';
        } else {
            $fileContent = '<?php
/**
 * Kuma Short Link - Generated by Simple KUMA
 * Use on landing page CTA buttons to mask your tracking URL.
 */

$targetUrl = "' . addslashes($urlToMask) . '";

header("Location: " . $targetUrl, true, 302);
exit;
?>';
        }
        
        // Send file as download
        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename="' . $fileName . '"');
        header('Content-Length: ' . strlen($fileContent));
        echo $fileContent;
        exit;
    }
}
?>

<div class="page-header">
    <h1 class="page-title">Short Links</h1>
    <p class="page-description">Generate Kuma short-link redirect files to mask tracking URLs in landing page CTAs.</p>
</div>

<div class="card">
    <div class="card-header">
        <h2 class="card-title" style="display: flex; align-items: center; gap: 8px;">
            <img src="<?= ASSETS_BASE_URL ?>/assets/images/cloakedbear.png" alt="Short Links" style="width: 24px; height: 24px;">
            Create Kuma Short Link
        </h2>
    </div>
    <div class="card-body">
        <p style="color: #666; margin-bottom: 24px; line-height: 1.6;">
            Generate a simple redirect page that hides your tracking URL behind a friendly path on your domain.
            Perfect for CTA buttons on landing pages — visitors see your domain, not the full <code>/km/</code> link.
        </p>

        <div style="background: #e7f3ff; border: 1px solid #b3d9ff; border-radius: 4px; padding: 16px; margin-bottom: 24px;">
            <strong style="color: #004085; display: block; margin-bottom: 8px;">📖 How It Works:</strong>
            <div style="font-family: monospace; font-size: 14px; color: #004085;">
                <div style="margin-bottom: 4px;"><strong>Original Tracking URL:</strong> <code>https://tracker.example.com/km/abc123xyz</code></div>
                <div style="margin-bottom: 4px;"><strong>Masked URL (on your domain):</strong> <code>https://yourdomain.com/go/start</code></div>
                <div style="margin-top: 8px; color: #666; font-size: 13px;">
                    Upload the generated redirect file to your server at <code>yourdomain.com/go/start.php</code>. When visitors 
                    click your CTA button using this URL, they'll be seamlessly redirected to your actual tracking link without 
                    exposing it in the browser address bar.
                </div>
            </div>
        </div>

        <?php if (isset($error)): ?>
            <div style="background: #f8d7da; border: 1px solid #f5c6cb; color: #721c24; padding: 12px; border-radius: 4px; margin-bottom: 20px;">
                ⚠️ <?= htmlspecialchars($error) ?>
            </div>
        <?php endif; ?>

        <form method="POST" action="">
            <input type="hidden" name="action" value="generate">
            
            <div style="margin-bottom: 24px;">
                <label for="url_to_mask" style="display: block; font-weight: 600; margin-bottom: 8px; color: #333;">
                    URL to Mask
                </label>
                <div style="display: flex; gap: 8px;">
                    <input 
                        type="url" 
                        id="url_to_mask" 
                        name="url_to_mask" 
                        value="<?= htmlspecialchars($_POST['url_to_mask'] ?? '') ?>"
                        placeholder="https://tracker.example.com/km/abc123xyz"
                        required
                        style="flex: 1; padding: 12px; border: 2px solid #ddd; border-radius: 4px; font-size: 14px; font-family: monospace;"
                    >
                </div>
            </div>

            <div style="margin-bottom: 24px;">
                <label style="display: flex; align-items: center; gap: 8px; cursor: pointer;">
                    <input 
                        type="checkbox" 
                        id="pass_parameters" 
                        name="pass_parameters" 
                        value="1"
                        <?= (isset($_POST['pass_parameters']) && $_POST['pass_parameters'] === '1') ? 'checked' : '' ?>
                    >
                    <span style="font-weight: 600; color: #333;">Pass Parameters</span>
                </label>
                <div style="font-size: 12px; color: #666; margin-top: 4px; margin-left: 24px;">
                    If enabled, all query parameters from the short link URL will be appended to the target tracking URL.
                </div>
            </div>

            <button type="submit" class="btn btn-primary" style="display: inline-flex; align-items: center; gap: 8px;">
                <span>🔄</span>
                <span>Generate</span>
            </button>
        </form>
    </div>
</div>


